### ISSUE TITLE
[🚀for settings]: add ability to control the width

### ISSUE THREAD

**Issue by yadamskaya** [exadel-inc/ui-playground#305]
As a UIplayground consumer, I want to have the ability to control the width of the Settings module.
**Expected Result:** The Preview module becomes narrower, and the Settings module is wider. The Settings module has a minimum width (which is now).

**Note:** This is a feature only for the desktop version, because on mobiles the Settings module has a width of 100%.

**Comment by ala-n** [comment]
Done within v2.0.0-beta.2-4
