### ISSUE TITLE
[🚀for preview]: replace browser scroll with esl scrollbar

### ISSUE THREAD

**Issue by yadamskaya** [exadel-inc/ui-playground#406]
When you resize the preview the browser scroll appears. Replace this scroll with esl scrollbar
**Note:** If you use the standard way of adding the esll scrollbar, then the resize feature disappears.
In our case, instead of using a `esl-scrollable-content` class, we need to create our own `scrollable-content` class so that the feature works.

**Comment by ala-n** [comment]
Resolved on v2.0.0-beta.2
